version: '3.8'
services:
  db:
    image: postgres:13
    container_name: auth-db-production  
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data   
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    image: abdum1964/auth-service:production
    container_name: auth-service-production   
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env   
    restart: unless-stopped
    ports:
      - "5003:5003"

volumes:
  postgres_data: