version: '3.8'
services:
  auth-service:
    image: abdum1964/auth-service:staging
    container_name: auth-service-staging   
       
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env   
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:13
    container_name: auth-db-staging  
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data   
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d auth_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: