services:
  annotation_service:
    image: ${DOCKER_IMAGE_PRODUCTION}
    container_name: annotation-service-production   
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env   
    command: flask run --host=0.0.0.0 --port=${APP_PORT}
    restart: always
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=${MONGO_URI}
      - APP_PORT=${APP_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  mongodb:
    image: mongo:latest
    container_name: mongodb-production   
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGODB_DOCKER_PORT}:27017"
    restart: always

  redis:
    image: redis:latest
    container_name: redis-production   
    ports:
      - "${REDIS_HOST}:${REDIS_PORT}"
    restart: always
    volumes:
      - redis_data:/data

  caddy:
    image: caddy:latest
    container_name: caddy-production   
    ports:
      - "${CADDY_PORT}:${CADDY_PORT_FORWARD}"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env   
    command: caddy reverse-proxy --from http://0.0.0.0:${CADDY_PORT} --to http://annotation_service:${APP_PORT}
    restart: always
    depends_on:
      - annotation_service

volumes:
  mongo_data:
  redis_data:
  caddy_data:
  caddy_config: