# roles/biocypher/tasks/main.yml
- name: Fix dpkg if interrupted
  command: sudo dpkg --configure -a
  ignore_errors: yes

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Python and Git
  apt:
    name: [python3, python3-pip, git]
    state: present

- name: Clone the AI_Assistant repository
  git:
    repo: https://github.com/rejuve-bio/AI-Assistant.git
    dest: /home/RejuveBio/AI_Assistant
    version: main

- name: Print Hello from AI_Assistant role
  debug:
    msg: "Ansible role 'AI_Assistant'working correctly!"
