services:
  assistant:
    image: ${ai_assistant_production}
    ports:
      - "${FLASK_HOST_PORT}:${FLASK_INTERNAL_PORT}"
    command: >
      sh -c "
      gunicorn -w 4 --bind 0.0.0.0:${FLASK_INTERNAL_PORT} --timeout 180 --log-level debug run:app
      "
    restart: always
    depends_on:
      - qdrant
      - redis
    environment:
      - .env

  qdrant:
    image: qdrant/qdrant:latest
    ports: 
      - "${QDRANT_HOST_PORT}:${QDRANT_INTERNAL_PORT}"
      - "${QDRANT_GRPC_HOST_PORT}:${QDRANT_GRPC_INTERNAL_PORT}"
     

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_INTERNAL_PORT}"
volumes:
  vectordata:
  mongodb_data: