# deploy_UI.yml
- name: Deploy UI Service
  hosts: UI_Local
  tags: UI_Local
  become: true
  roles:
    - UI

# deploy_custom_atomspace.yml
- name: Custom Atomspace builder_Local
  hosts: Custom_Atomspace_builder_Local
  tags: Custom_Atomspace_builder_Local
  become: true
  roles:
    - Custom_Atomspace_builder
  
  ## deploy_annotation.yml
- name: Deploy Annotation Service
  hosts: annotation_Local
  tags: annotation_Local
  become: true
  roles:
    - Annotation

#Remote_Deployment

- name: Deploy UI Service
  hosts: UI_Remote
  tags: UI_Remote
  become: true
  roles:
    - UI

# deploy_custom_atomspace.yml
- name: Custom Atomspace builder_Remote
  hosts: Custom_Atomspace_builder_Remote
  tags: Custom_Atomspace_builder_Remote
  become: true
  roles:
    - Custom_Atomspace_builder
  
  ## deploy_annotation.yml
- name: Deploy Annotation Service
  hosts: annotation_Remote
  tags: annotation_Remote
  become: true
  roles:
    - Annotation



