
- name: Deploy UI Service
  hosts: UI_Local
  tags: UI_Local
  become: true
  roles:
    - UI
# deploy_custom_atomspace.yml
- name: Custom Atomspace builder_Local
  hosts: Custom_Atomspace_builder_Local
  roles:
    - Custom_Atomspace_builder
  tags: Custom_Atomspace_builder_Local
  become: true
  
  ## deploy_annotation.yml
- name: Deploy Annotation Service
  hosts: annotation_Local
  tags: annotation_Local
  become: true
  roles:
    - Annotation


