# roles/annotation/tasks/main.yml
- name: Fix dpkg if interrupted
  command: sudo dpkg --configure -a
  ignore_errors: yes

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required system packages
  apt:
    name: [docker.io, docker-compose, python3, python3-pip, git]
    state: present
    update_cache: yes

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Create project directory
  file:
    path: /home/RejuveBio/Annotation
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Clone the Annotation repository
  git:
    repo: https://github.com/rejuve-bio/annotation-query-backend-general.git
    dest: /home/RejuveBio/Annotation
    version: main
    force: yes

- name: Modify requirements.txt
  replace:
    path: /home/RejuveBio/Annotation/requirements.txt
    regexp: '^biocypher>=0\.5\.4$'
    replace: 'biocypher==0.5.4\npandas>=1.3.0'
    backup: yes

- name: Create required data directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
    - /home/RejuveBio/Annotation/metta_data
    - /home/RejuveBio/Annotation/cypher_data

- name: Copy pre-configured .env file to remote
  copy:
    src: templates/.env
    dest: /home/RejuveBio/Annotation/.env
    mode: '0640'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Clean up existing containers (with sudo)
  shell: |
    sudo docker-compose -f /home/RejuveBio/Annotation/docker-compose.yml down -v
  args:
    executable: /bin/bash
  ignore_errors: yes
  register: cleanup
  changed_when: "'Stopping' in cleanup.stdout"

- name: Build and start containers (with sudo)
  shell: |
    cd /home/RejuveBio/Annotation
    sudo docker-compose up --build -d
  args:
    executable: /bin/bash
  register: compose_up
  retries: 2
  delay: 10
  until: compose_up.rc == 0

- name: Verify container status
  shell: |
    sudo docker ps --filter "name=annotation_service" --format "{{ '{{.Names}} {{.Status}}' }}"
  register: container_status
  until: "'Up' in container_status.stdout"
  retries: 5
  delay: 10
  failed_when: "'Restarting' in container_status.stdout"

- name: Get container logs if verification fails
  shell: |
    sudo docker logs annotation_annotation_service_1 --tail 50
  register: container_logs
  when: container_status.failed
  changed_when: false

- name: Display container logs if deployment failed
  debug:
    var: container_logs.stdout_lines
  when: container_status.failed

- name: Print deployment success message
  debug:
    msg: "Annotation service deployed successfully and running on port 5800 | 6100"